name: Terraform Security Scan


on:

  push:

    branches:

      - main

  pull_request:

    branches:

      - main



permissions:

  contents: read

  security-events: write



jobs:


  terraform-security:


    name: Terraform Security Checks


    runs-on: ubuntu-latest



    steps:


      ###################################################
      # Checkout Code
      ###################################################

      - name: Checkout Repository

        uses: actions/checkout@v4



      ###################################################
      # Install Terraform
      ###################################################

      - name: Setup Terraform

        uses: hashicorp/setup-terraform@v3



      ###################################################
      # Terraform Format Check
      ###################################################

      - name: Terraform Format Check

        run: terraform fmt -check -recursive



      ###################################################
      # Terraform Init
      ###################################################

      - name: Terraform Init

        run: terraform init



      ###################################################
      # Terraform Validate
      ###################################################

      - name: Terraform Validate

        run: terraform validate



      ###################################################
      # Install Checkov
      ###################################################

      - name: Install Checkov

        run: |

          pip install checkov



      ###################################################
      # Run Checkov
      ###################################################

      - name: Checkov Security Scan

        run: |

          checkov \
          -d . \
          --framework terraform \
          --output cli



      ###################################################
      # Install tfsec
      ###################################################

      - name: Install tfsec

        run: |

          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash



      ###################################################
      # Run tfsec
      ###################################################

      - name: tfsec Terraform Scan

        run: |

          tfsec .

          